#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
import sys
import time
import tkinter as tk
from pathlib import Path
from tkinter import ttk


APP_DIR = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "rvveber-fhud"
STATE_DIR = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local" / "state")) / "rvveber-fhud"
SETTINGS_PATH = APP_DIR / "nightshift-tuner.json"
SHADER_PATH = STATE_DIR / "nightshift-tuned.glsl"

DEFAULTS = {
    "temperature": 3000,
    "strength": 72,
    "green": 62,
    "blue": 24,
    "saturation": 86,
    "contrast": 100,
    "cool_desaturate": 38,
}

SLIDERS = [
    ("temperature", "Temperature", 1800, 6500, "K"),
    ("strength", "Warmth", 0, 100, "%"),
    ("green", "Green detail", 0, 100, "%"),
    ("blue", "Blue detail", 0, 100, "%"),
    ("saturation", "Color saturation", 0, 120, "%"),
    ("contrast", "Contrast", 80, 120, "%"),
    ("cool_desaturate", "Cool-color gray rescue", 0, 100, "%"),
]


def clamp(value, low, high):
    return max(low, min(high, value))


def load_settings():
    settings = DEFAULTS.copy()
    try:
        with SETTINGS_PATH.open() as handle:
            raw = json.load(handle)
    except FileNotFoundError:
        return settings
    except (OSError, json.JSONDecodeError) as error:
        print(f"Could not read {SETTINGS_PATH}: {error}", file=sys.stderr)
        return settings

    for key, _, low, high, _ in SLIDERS:
        if key in raw:
            settings[key] = int(clamp(float(raw[key]), low, high))
    return settings


def save_settings(settings):
    APP_DIR.mkdir(parents=True, exist_ok=True)
    with SETTINGS_PATH.open("w") as handle:
        json.dump(settings, handle, indent=2, sort_keys=True)
        handle.write("\n")


def score(settings):
    strength = settings["strength"] / 100.0
    blue = settings["blue"] / 100.0
    green = settings["green"] / 100.0
    temp_factor = clamp((settings["temperature"] - 1800) / (6500 - 1800), 0.0, 1.0)
    leak = 100.0 * strength * (0.70 * blue + 0.20 * green + 0.10 * temp_factor)
    color = 100.0 * (0.55 * blue + 0.30 * green + 0.15 * settings["saturation"] / 100.0)
    return round(leak), round(clamp(color, 0.0, 100.0))


def shader_text(settings):
    temperature = settings["temperature"]
    strength = settings["strength"] / 100.0
    green = settings["green"] / 100.0
    blue = settings["blue"] / 100.0
    saturation = settings["saturation"] / 100.0
    contrast = settings["contrast"] / 100.0
    cool_desaturate = settings["cool_desaturate"] / 100.0

    return f"""// Generated by rvveber-fhud-nightshift-tuner. Edit with the tuner, not by hand.
#version 300 es
precision highp float;

in vec2 v_texcoord;
uniform sampler2D tex;
out vec4 fragColor;

const float temperature = {temperature:.1f};
const float temperatureStrength = {strength:.4f};
const vec3 channelScale = vec3(1.0, {green:.4f}, {blue:.4f});
const float saturationScale = {saturation:.4f};
const float contrastScale = {contrast:.4f};
const float coolDesaturate = {cool_desaturate:.4f};
const float LuminancePreservationFactor = 1.0;

vec3 colorTemperatureToRGB(const in float temperature) {{
    mat3 m = (temperature <= 6500.0)
        ? mat3(vec3(0.0, -2902.1955373783176, -8257.7997278925690),
               vec3(0.0, 1669.5803561666639, 2575.2827530017594),
               vec3(1.0, 1.3302673723350029, 1.8993753891711275))
        : mat3(vec3(1745.0425298314172, 1216.6168361476490, -8257.7997278925690),
               vec3(-2666.3474220535695, -2173.1012343082230, 2575.2827530017594),
               vec3(0.55995389139931482, 0.70381203140554553, 1.8993753891711275));

    return mix(
        clamp(m[0] / (vec3(clamp(temperature, 1000.0, 40000.0)) + m[1]) + m[2], 0.0, 1.0),
        vec3(1.0),
        smoothstep(1000.0, 0.0, temperature)
    );
}}

void main() {{
    vec4 pixColor = texture(tex, v_texcoord);
    vec3 color = pixColor.rgb;

    float lum = dot(color, vec3(0.2126, 0.7152, 0.0722));
    color *= mix(1.0, lum / max(lum, 1e-5), LuminancePreservationFactor);

    float cool = max(color.b - max(color.r, color.g), 0.0);
    float clippedMask = smoothstep(0.02, 0.20, cool) * coolDesaturate;
    vec3 pre = mix(color, vec3(lum), clippedMask);

    vec3 warmMul = colorTemperatureToRGB(temperature);
    vec3 outColor = mix(pre, pre * warmMul, temperatureStrength);
    outColor *= mix(vec3(1.0), channelScale, temperatureStrength);

    float outLum = dot(outColor, vec3(0.2126, 0.7152, 0.0722));
    outColor = mix(vec3(outLum), outColor, saturationScale);
    outColor = (outColor - 0.5) * contrastScale + 0.5;

    fragColor = vec4(clamp(outColor, 0.0, 1.0), pixColor.a);
}}
"""


def write_shader(settings):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    SHADER_PATH.write_text(shader_text(settings))
    return SHADER_PATH


def apply_shader(settings):
    path = write_shader(settings)
    subprocess.run(["hyprshade", "on", str(path)], check=False)


def turn_off():
    subprocess.run(["hyprshade", "off"], check=False)


def parse_clock(value):
    parts = [int(part) for part in value.split(":")]
    while len(parts) < 3:
        parts.append(0)
    return parts[0] * 3600 + parts[1] * 60 + parts[2]


def within_window(now, start, end):
    if start <= end:
        return start <= now < end
    return now >= start or now < end


def auto_apply(start_time, end_time):
    now = time.localtime()
    seconds = now.tm_hour * 3600 + now.tm_min * 60 + now.tm_sec
    if within_window(seconds, parse_clock(start_time), parse_clock(end_time)):
        apply_shader(load_settings())
    else:
        turn_off()


class Tuner:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("Nightshift tuner")
        self.root.resizable(False, False)
        self.settings = load_settings()
        self.vars = {}
        self.debounce_id = None

        frame = ttk.Frame(self.root, padding=14)
        frame.grid(row=0, column=0, sticky="nsew")

        ttk.Label(frame, text="Tune for the lowest blue/cyan leak that still preserves game colors.").grid(
            row=0, column=0, columnspan=3, sticky="w", pady=(0, 10)
        )

        for row, (key, label, low, high, unit) in enumerate(SLIDERS, start=1):
            var = tk.IntVar(value=self.settings[key])
            self.vars[key] = var
            ttk.Label(frame, text=label).grid(row=row, column=0, sticky="w", padx=(0, 10), pady=3)
            scale = ttk.Scale(frame, from_=low, to=high, orient="horizontal", variable=var, command=self.changed)
            scale.grid(row=row, column=1, sticky="ew", pady=3)
            value = ttk.Label(frame, width=9)
            value.grid(row=row, column=2, sticky="e", padx=(10, 0))

            def update_value(*_, current_var=var, target=value, suffix=unit):
                target.configure(text=f"{current_var.get()}{suffix}")

            var.trace_add("write", update_value)
            update_value()

        frame.columnconfigure(1, minsize=260)
        self.metric = ttk.Label(frame)
        self.metric.grid(row=len(SLIDERS) + 1, column=0, columnspan=3, sticky="w", pady=(10, 8))

        buttons = ttk.Frame(frame)
        buttons.grid(row=len(SLIDERS) + 2, column=0, columnspan=3, sticky="ew")
        ttk.Button(buttons, text="Apply now", command=self.apply_now).pack(side="left")
        ttk.Button(buttons, text="Save", command=self.save).pack(side="left", padx=8)
        ttk.Button(buttons, text="Off", command=turn_off).pack(side="left")
        ttk.Button(buttons, text="Quit", command=self.root.destroy).pack(side="right")

        self.update_metric()
        self.apply_now()

    def current_settings(self):
        return {key: int(var.get()) for key, var in self.vars.items()}

    def changed(self, _value=None):
        self.settings = self.current_settings()
        self.update_metric()
        if self.debounce_id is not None:
            self.root.after_cancel(self.debounce_id)
        self.debounce_id = self.root.after(250, self.apply_now)

    def update_metric(self):
        leak, color = score(self.current_settings())
        self.metric.configure(text=f"Blue/cyan leak score: {leak}/100 lower is warmer | Color detail score: {color}/100 higher is easier to play")

    def apply_now(self):
        self.debounce_id = None
        self.settings = self.current_settings()
        apply_shader(self.settings)

    def save(self):
        self.settings = self.current_settings()
        save_settings(self.settings)
        apply_shader(self.settings)

    def run(self):
        self.root.mainloop()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--auto", nargs=2, metavar=("START", "END"), help="apply saved shader only inside the scheduled time window")
    parser.add_argument("--apply-saved", action="store_true", help="write and apply saved settings")
    parser.add_argument("--off", action="store_true", help="turn the shader off")
    args = parser.parse_args()

    if args.auto:
        auto_apply(args.auto[0], args.auto[1])
    elif args.apply_saved:
        apply_shader(load_settings())
    elif args.off:
        turn_off()
    else:
        Tuner().run()


if __name__ == "__main__":
    main()
