creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - "age1f9jcxq4enfn5sk6slelq7zxfz8qdzs0usqtkjaflxmk6xmz9ayaqxvt8tf" #friday
      - "age1rx04xr2h30ltr3cnsf9tkagpehpzu43uaz0gxktjr4wq7wg0hdhsmf97dr" #b1kini